Repository marcauberer/compiler-design-lecture-project-TINF23B6, pull requests merged in 2025-04, with the labels that each got.

#23 Parser - Team 7
  .run/Run Default.run.xml
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTAnonymousBlockStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTVisitor.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
Labels: size/M

#26 Parser - Team 3
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTDoWhileLoopNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTVisitor.java
  src/main/java/com/auberer/compilerdesignlectureproject/lexer/TokenType.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
Labels: size/M

#30 Parser - Team 2
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTVisitor.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTWhileLoopStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/lexer/StringLiteralStateMachine.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
  src/main/java/com/auberer/compilerdesignlectureproject/reader/Reader.java
  src/test/java/com/auberer/compilerdesignlectureproject/lexer/IdentifierLiteralStateMachineTest.java
  src/test/java/com/auberer/compilerdesignlectureproject/lexer/KeywordLiteralStateMachineTest.java
  src/test/java/com/auberer/compilerdesignlectureproject/lexer/StringLiteralStateMachineTest.java
Labels: size/L

#31 Parser - Team 5
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTForLoopNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTVisitor.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
Labels: size/M

#33 Parser - Team 6
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTCaseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTDefaultStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTSwitchCaseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTVisitor.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
Labels: size/L

#29 Parser - Team 4
  TInf.g4
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/gen/TInf.interp
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/gen/TInf.tokens
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/gen/TInfLexer.interp
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/gen/TInfLexer.java
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/gen/TInfLexer.tokens
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/gen/TInfParser.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTArgLstNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionCallNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionDefNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTParamLstNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTParamNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTReturnStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
  src/test/java/com/auberer/compilerdesignlectureproject/lexer/DoubleLiteralStateMachineTest.java
Labels: size/XL

#34 More beautiful double
  src/main/java/com/auberer/compilerdesignlectureproject/lexer/DoubleLiteralStateMachine.java
  src/test/java/com/auberer/compilerdesignlectureproject/lexer/DoubleLiteralStateMachineTest.java
Labels: size/M

#32 Parser - Team 1
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTElseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTIfBodyNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTIfStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTVisitor.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
Labels: size/L

#35 ASTBuilder - Team 7
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/ASTBuilder.java
Labels: size/S

#37 ASTBuilder - Team 1
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/ASTBuilder.java
Labels: size/M

#40 ASTBuilder - Team 3
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/ASTBuilder.java
Labels: size/S
