Repository marcauberer/compiler-design-lecture-project-TINF23B6, pull requests merged in 2025-05, with the labels that each got.

#42 ASTBuilder - Team 4
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/ASTBuilder.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionCallNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionDefNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
  test.tinf
Labels: size/L

#43 AST Helpers - Team 7
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTAnonymousBlockStmtNode.java
  src/test-e2e/anonymous-block-stmnt-antlr-parser/args.txt
  src/test-e2e/anonymous-block-stmnt-antlr-parser/out.txt
  src/test-e2e/anonymous-block-stmnt-antlr-parser/source.tinf
  src/test-e2e/anonymous-block-stmnt-own-parser/args.txt
  src/test-e2e/anonymous-block-stmnt-own-parser/out.txt
  src/test-e2e/anonymous-block-stmnt-own-parser/source.tinf
Labels: size/L

#47 AST Helpers - Team 1
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTElseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTIfBodyNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTIfStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
  src/test-e2e/if-stmt-antlr/args.txt
  src/test-e2e/if-stmt-antlr/out.txt
  src/test-e2e/if-stmt-antlr/source.tinf
  src/test-e2e/if-stmt-own-parser/args.txt
  src/test-e2e/if-stmt-own-parser/out.txt
  src/test-e2e/if-stmt-own-parser/source.tinf
Labels: size/L

#45 AST Helpers - Team 6
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTCaseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTDefaultStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTSwitchCaseStmtNode.java
  src/test-e2e/switch-case-stmnt-antlr-parser/args.txt
  src/test-e2e/switch-case-stmnt-antlr-parser/out.txt
  src/test-e2e/switch-case-stmnt-antlr-parser/source.tinf
  src/test-e2e/switch-case-stmnt-own-parser/args.txt
  src/test-e2e/switch-case-stmnt-own-parser/out.txt
  src/test-e2e/switch-case-stmnt-own-parser/source.tinf
Labels: size/L

#44 AST Helpers - Team 5
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTForLoopNode.java
  src/test-e2e/for-loop-antlr/args.txt
  src/test-e2e/for-loop-antlr/out.txt
  src/test-e2e/for-loop-antlr/source.tinf
  src/test-e2e/for-loop-test/args.txt
  src/test-e2e/for-loop-test/out.txt
  src/test-e2e/for-loop-test/source.tinf
Labels: size/L

#46 AST Helpers - Team 3
  src/test-e2e/antlr-do-while-loop/args.txt
  src/test-e2e/antlr-do-while-loop/out.txt
  src/test-e2e/antlr-do-while-loop/source.tinf
  src/test-e2e/test-do-while-loop/args.txt
  src/test-e2e/test-do-while-loop/out.txt
  src/test-e2e/test-do-while-loop/source.tinf
Labels: size/L

#48 AST - Helpers - Team 2
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTWhileLoopStmtNode.java
  src/test-e2e/while-antlr-parser/args.txt
  src/test-e2e/while-antlr-parser/out.txt
  src/test-e2e/while-antlr-parser/source.tinf
  src/test-e2e/while-own-parser/args.txt
  src/test-e2e/while-own-parser/out.txt
  src/test-e2e/while-own-parser/source.tinf
Labels: size/XL

#49 AST Helpers - Team 4
  src/main/java/com/auberer/compilerdesignlectureproject/antlr/ASTBuilder.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTArgLstNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionCallNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionDefNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTParamLstNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTParamNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTReturnStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/parser/Parser.java
  src/test-e2e/antlr-funccall-parser-test/args.txt
  src/test-e2e/antlr-funccall-parser-test/out.txt
  src/test-e2e/antlr-funccall-parser-test/source.tinf
  src/test-e2e/antlr-funcdef-parser-test/args.txt
  src/test-e2e/antlr-funcdef-parser-test/out.txt
  src/test-e2e/antlr-funcdef-parser-test/source.tinf
  src/test-e2e/own-funccall-parser-test/args.txt
  src/test-e2e/own-funccall-parser-test/out.txt
  src/test-e2e/own-funccall-parser-test/source.tinf
  src/test-e2e/own-funcdef-parser-test/args.txt
  src/test-e2e/own-funcdef-parser-test/out.txt
  src/test-e2e/own-funcdef-parser-test/source.tinf
Labels: size/L

#51 Added visit for creating symbol tables and added tests
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/anonymous-block-stmt-symbol-table/args.txt
  src/test-e2e/anonymous-block-stmt-symbol-table/out.txt
  src/test-e2e/anonymous-block-stmt-symbol-table/source.tinf
Labels: size/M

#54 Symbol Table Builder - Team 3
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/do-while-loop-symbol-table/args.txt
  src/test-e2e/do-while-loop-symbol-table/out.txt
  src/test-e2e/do-while-loop-symbol-table/source.tinf
Labels: size/M

#53 Symbol Table Builder - Team 6
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/switch-case-stmt-symbol-table/args.txt
  src/test-e2e/switch-case-stmt-symbol-table/out.txt
  src/test-e2e/switch-case-stmt-symbol-table/source.tinf
Labels: size/M

#55 Symbol Table Builder - Team 1
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/if-stmt-symbol-table/args.txt
  src/test-e2e/if-stmt-symbol-table/out.txt
  src/test-e2e/if-stmt-symbol-table/source.tinf
Labels: size/M

#56 Symbol Table Builder - Team 5
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/for-loop-symbol-table-sema/args.txt
  src/test-e2e/for-loop-symbol-table-sema/out.txt
  src/test-e2e/for-loop-symbol-table-sema/source.tinf
Labels: size/M

#57 Symbol Table Builder - Team 2
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/while-loop-symbol-table/args.txt
  src/test-e2e/while-loop-symbol-table/out.txt
  src/test-e2e/while-loop-symbol-table/source.tinf
Labels: size/M

#58 Symbol Table Builder - Team 4
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionDefNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTParamNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/anonymous-block-stmt-symbol-table/out.txt
  src/test-e2e/do-while-loop-symbol-table/out.txt
  src/test-e2e/do-while-loop-symbol-table/source.tinf
  src/test-e2e/do-while-own-parser/out.txt
  src/test-e2e/do-while-own-parser/source.tinf
  src/test-e2e/for-loop-symbol-table-sema/out.txt
  src/test-e2e/function-symbol-table/args.txt
  src/test-e2e/function-symbol-table/out.txt
  src/test-e2e/function-symbol-table/source.tinf
  src/test-e2e/if-stmt-symbol-table/out.txt
  src/test-e2e/switch-case-stmt-symbol-table/out.txt
  src/test-e2e/while-loop-symbol-table/out.txt
  src/test-e2e/while-loop-symbol-table/source.tinf
Labels: size/L

#64 TypeChecker - Team 4
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionDefNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTParamNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/FunctionTable.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/FunctionTableEntry.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
  src/test-e2e/function-symbol-table/out.txt
  src/test-e2e/function-symbol-table/source.tinf
Labels: size/L

#65 TypeChecker - Team 6
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTCaseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTSwitchCaseStmtNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
  src/test-e2e/switch-case-stmt-symbol-table/source.tinf
  src/test-e2e/switch-case-stmt-type-checker-fail/args.txt
  src/test-e2e/switch-case-stmt-type-checker-fail/out.txt
  src/test-e2e/switch-case-stmt-type-checker-fail/source.tinf
  src/test-e2e/switch-case-stmt-type-checker/args.txt
  src/test-e2e/switch-case-stmt-type-checker/out.txt
  src/test-e2e/switch-case-stmt-type-checker/source.tinf
Labels: size/L

#67 Type Checker - Team 4
  src/main/java/com/auberer/compilerdesignlectureproject/CompilerDesignLectureProject.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
  src/test-e2e/function-type-checker-wrong-arg-amount/args.txt
  src/test-e2e/function-type-checker-wrong-arg-amount/out.txt
  src/test-e2e/function-type-checker-wrong-arg-amount/source.tinf
  src/test-e2e/function-type-checker-wrong-return-stmt/args.txt
  src/test-e2e/function-type-checker-wrong-return-stmt/out.txt
  src/test-e2e/function-type-checker-wrong-return-stmt/source.tinf
  src/test-e2e/function-type-checker-wrong-return-type/args.txt
  src/test-e2e/function-type-checker-wrong-return-type/out.txt
  src/test-e2e/function-type-checker-wrong-return-type/source.tinf
  src/test-e2e/function-type-checker/args.txt
  src/test-e2e/function-type-checker/out.txt
  src/test-e2e/function-type-checker/source.tinf
  src/test-e2e/helptext-test/out.txt
Labels: size/L

#68 TypeChecker - Team 2
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTWhileLoopNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
  src/test-e2e/while-loop-type-checker/args.txt
  src/test-e2e/while-loop-type-checker/out.txt
  src/test-e2e/while-loop-type-checker/source.tinf
Labels: size/L

#70 Code Generator | Group 7
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
Labels: size/S

#73 IR Generator - Team 3
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
Labels: size/S
