Repository marcauberer/compiler-design-lecture-project-TINF23B6, pull requests merged in 2025-06, with the labels that each got.

#77 IR Generator - Team 2
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
Labels: size/S

#74 Code improvements - Team 4
  src/main/java/com/auberer/compilerdesignlectureproject/sema/FunctionTable.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/FunctionTableEntry.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
  src/test-e2e/function-type-checker-wrong-arg-amount/out.txt
Labels: size/L

#75 IRGenerator - Team 1
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
Labels: size/S

#76 IR Function - Team 4 (struggling need help)
  src/main/java/com/auberer/compilerdesignlectureproject/CompilerDesignLectureProject.java
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTFunctionCallNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/BasicBlock.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
  src/main/java/com/auberer/compilerdesignlectureproject/sema/SymbolTableBuilder.java
  src/test-e2e/function-ir/args.txt
  src/test-e2e/function-ir/out.txt
  src/test-e2e/function-ir/source.tinf
Labels: size/M

#72 IR Generator - Team 6
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/SwitchInstruction.java
Labels: size/M

#82 Added IR test for anonymous block stmnt
  src/test-e2e/anonymous-block-stmt-ir/args.txt
  src/test-e2e/anonymous-block-stmt-ir/out.txt
  src/test-e2e/anonymous-block-stmt-ir/source.tinf
Labels: size/M

#86 IR Test - Team 1
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTIfBodyNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
  src/test-e2e/if-stmt-codegen/args.txt
  src/test-e2e/if-stmt-codegen/out.txt
  src/test-e2e/if-stmt-codegen/source.tinf
  src/test-e2e/if-stmt-own-parser/out.txt
Labels: size/M

#90 Fixed value bug
  src/main/java/com/auberer/compilerdesignlectureproject/ast/ASTNode.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/CodeGenerator.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/DivInstruction.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/LoadInstruction.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/MinusInstruction.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/MulInstruction.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/PlusInstruction.java
  src/main/java/com/auberer/compilerdesignlectureproject/codegen/instructions/StoreInstruction.java
  src/main/java/com/auberer/compilerdesignlectureproject/interpreter/Value.java
  test.tinf
Labels: size/M
